### PR TITLE
Update faq

### PR DESCRIPTION
**Pull request by MylesBorins**

### CODE REVIEW

**Comment by MylesBorins** [comment]
/cc @ljharb and @jkrems

This doesn't solve for the node use case regarding polyfills, but I think that is something that we can create a mechanism to fix as an embedder.

**Comment by jkrems** [comment]
Since polyfill ~= APM instrumentation, would the following become the standard way to start an application?

```js
// Ensure all global state is in good shape
import 'apm';
import 'polyfills';

// Start loading any app code
await import('./actual-app');
```

I guess some of this might also be solved via custom loaders but the above *seems* like it would support both node and the browser (minus efficiency in the browser because it's not as prefetch-friendly without additional meta tags).

**Comment by domenic** [comment]
There's no need for the third import to be dynamic, as long as the polyfills and apm modules do not themselves use top-level await (i.e. do not explicitly choose to yield to the event loop).

**Comment by jkrems** [comment]
Gotcha. The issue would only occur with, say:

```js
if (!Promise.finally) {
  await import('./polyfills');
}

if (process.env.NODE_ENV === 'production') {
  await import('apm');
}

await import('./actual-app.js');
```

**Pull request merged**
